# Generated by Django 5.1.7 on 2025-04-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='story_categories', to='stories.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.category', verbose_name='Главная категория'),
        ),
    ]
