# Generated by Django 5.1.7 on 2025-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ настройки')),
                ('value', models.TextField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        # Добавляем начальные данные
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('stories', 'SiteSettings').objects.create(
                key='token_purchase_url',
                value='https://example.com/token',
                description='URL для покупки токена'
            ),
            reverse_code=lambda apps, schema_editor: apps.get_model('stories', 'SiteSettings').objects.filter(
                key='token_purchase_url'
            ).delete()
        ),
    ]
