# Generated by Django 5.1.7 on 2025-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_crypto_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crypto_token',
            field=models.CharField(blank=True, default='TON', max_length=255, verbose_name='Токен для криптовалюты'),
        ),
    ]
