# Generated by Django 5.1.7 on 2025-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_crypto_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс токенов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokens_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего выплачено токенов'),
        ),
    ]
